In [63]:
import numpy as np
import tensorflow as tf 
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [64]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.50, 0.80, 0.30, 0.55, 0.70, 0.12, 0.30],
    
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 38, 30, 25, 20, 29],
    
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    
    "needs_water": [1, 1, 1, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1, 1]
})

In [65]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            1
7            0.18             22              10            0
8            0.45             35              12            1
9            0.50             24               5            0
10           0.80             33               9            1
11           0.30             38              11            0
12           0.55             30               2            0
13           0.70             25               6            1
14           0.12             20               1            1
15           0.30             29               9            1

In [66]:
X = df[['soil_moisture', 'temperature_c' , 'sunlight_hours']]
y = df['needs_water']

In [67]:
X_min = X.min()
X_max = X.max()

X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [68]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.000000       0.789474        0.727273
1        0.071429       0.578947        0.636364
2        0.142857       0.368421        0.545455
3        0.214286       0.157895        0.272727
4        0.428571       0.473684        0.636364
5        0.714286       0.578947        0.818182
6        0.357143       0.000000        0.181818
7        0.114286       0.157895        0.818182
8        0.500000       0.842105        1.000000
9        0.571429       0.263158        0.363636
10       1.000000       0.736842        0.727273
11       0.285714       1.000000        0.909091
12       0.642857       0.578947        0.090909
13       0.857143       0.315789        0.454545
14       0.028571       0.052632        0.000000
15       0.285714       0.526316        0.727273

In [69]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=42)

In [70]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8, activation='relu'),
    # Add more layers as per requirement
    layers.Dense(1, activation='sigmoid')
])

In [71]:
model.compile(optimizer='sgd' , loss = 'binary_crossentropy' , metrics= ['accuracy'])

In [72]:
history = model.fit(
    X_train.values,
    y_train.values,
    validation_data=(X_test.values, y_test.values),
    epochs=100,
    batch_size=4,
    verbose=0
)